version: "3.7"

networks:
  airflow:

x-dags-and-logs: &dags-and-logs
  - ./dags:/opt/airflow/dags
  - ./logs:/opt/airflow/logs
  - ./plugins:/opt/airflow/plugins
  - ./airflow-tutorial:/home/airflow/airflow-tutorial
  - ./maintenance:/home/airflow/maintenance

x-airflow-env:
  &dags-folder-env
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
  - AIRFLOW__WEBSERVER__BASE_URL=http://localhost
  - AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW=graph
  - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
  - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__CELERY__BROKER_URL=redis://@redis:6379/0
  - AIRFLOW__CLI__ENDPOINT_URL=http://localhost
  - AIRFLOW__METRICS__STATSD_ON=True
  - AIRFLOW__METRICS__STATSD_HOST=prometheus-statsd-exporter
  - AIRFLOW__METRICS__STATSD_PORT=9125
  - AIRFLOW__METRICS__STATSD_PREFIX=airflow
  - DAG_FOLDERS=/home/airflow/airflow-tutorial,/home/airflow/maintenance

x-airflow-common: &airflow-common
  image: airflow:2.2.3
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    *dags-folder-env
  env_file:
    - .env
  volumes:
    *dags-and-logs
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"
  depends_on:
    - redis
    - mysqldb
  networks:
    - airflow


services:

  mysqldb:
    image: mysql:8.0.27
    container_name: airflow-mysql-db
    command: --explicit_defaults_for_timestamp
    environment:
      MYSQL_ROOT_PASSWORD: "airflow"
      MYSQL_DATABASE: "airflow"
      MYSQL_USER: "airflow"
      MYSQL_PASSWORD: "airflow"
    volumes:
      - ./database/mysql-datadir:/var/lib/mysql
    networks:
      - airflow

  redis:
    image: redis:6.2.6
    container_name: airflow-redis
    networks:
      - airflow

  webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    ports:
      - 80:8080
    command: webserver

  scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler

  worker:
    <<: *airflow-common
    container_name: airflow-worker
    command: celery worker

  db_upgrade:
    <<: *airflow-common
    container_name: airflow-db-upgrade
    command: db upgrade

  flower:
    <<: *airflow-common
    container_name: airflow-flower
    ports:
      - 5555:5555
    command: celery flower

  initdb:
    <<: *airflow-common
    container_name: airflow-initdb
    volumes:
      - ./wait-for-it.sh:/opt/airflow/wait-for-it.sh
    entrypoint: /bin/bash
    user: "50000:50000"
    command:
      - -c
      - |
        /opt/airflow/wait-for-it.sh mysqldb:3306 -- echo "mysql is up"
        airflow db init
        airflow users create --firstname Jose --lastname Nunes --email admin --password admin --username admin --role Admin
  
  prometheus-statsd-exporter:
    image: prom/statsd-exporter:v0.22.2
    container_name: prom-statsd-exporter
    ports: 
      - 9102:9102
    networks: 
      - airflow
    command: ["--log.level=debug"]
