version: "3.8"

networks:
  airflow:

x-dags-and-logs: &dags-and-logs
  - ./dags:/opt/airflow/dags
  - ./logs:/opt/airflow/logs
  - ./plugins:/opt/airflow/plugins
  - ./airflow_tutorial:/home/airflow/airflow_tutorial
  - ./ge:/home/airflow/ge
  - ./maintenance:/home/airflow/maintenance

x-airflow-env:
  &dags-folder-env
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
  - AIRFLOW__WEBSERVER__BASE_URL=http://localhost
  - AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW=graph
  - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
  - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
  - AIRFLOW__CELERY__BROKER_URL=redis://@redis:6379/0
  - AIRFLOW__CLI__ENDPOINT_URL=http://localhost
  - AIRFLOW__METRICS__STATSD_ON=True
  - AIRFLOW__METRICS__STATSD_HOST=prometheus-statsd-exporter
  - AIRFLOW__METRICS__STATSD_PORT=9125
  - AIRFLOW__METRICS__STATSD_PREFIX=airflow
  - DAG_FOLDERS=/home/airflow/airflow_tutorial,/home/airflow/ge,/home/airflow/maintenance

x-airflow-common: &airflow-common
  image: airflow:2.7.3
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    *dags-folder-env
  env_file:
    - .env
  volumes:
    *dags-and-logs
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"
  depends_on:
    - redis
    - database
  networks:
    - airflow


services:

  # database:
  #   image: mysql:8.1.0
  #   container_name: airflow-db
  #   command: --explicit_defaults_for_timestamp
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "airflow"
  #     MYSQL_DATABASE: "airflow"
  #     MYSQL_USER: "airflow"
  #     MYSQL_PASSWORD: "airflow"
  #   volumes:
  #     - ./database/mysql-datadir:/var/lib/mysql
  #   networks:
  #     - airflow

  database:
    image: postgres:16.1
    container_name: airflow-db
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    #   - ./database/pg-data:/var/lib/postgresql/data
    networks:
      - airflow
    # command: postgres -c log_min_error_statement=fatal -c wal_level=logical -c max_wal_senders=10 -c max_replication_slots=1

  pgadmin:
    image: dpage/pgadmin4:8.0
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8081:80
    networks:
      - airflow

  redis:
    image: redis:7.2.1
    container_name: airflow-redis
    networks:
      - airflow

  webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    ports:
      - 80:8080
    command: webserver

  scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler

  worker:
    <<: *airflow-common
    container_name: airflow-worker
    command: celery worker

  db_upgrade:
    <<: *airflow-common
    container_name: airflow-db-upgrade
    command: db upgrade

  flower:
    <<: *airflow-common
    container_name: airflow-flower
    ports:
      - 5555:5555
    command: celery flower

  initdb:
    <<: *airflow-common
    container_name: airflow-initdb
    volumes:
      - ./wait-for-it.sh:/opt/airflow/wait-for-it.sh
    entrypoint: /bin/bash
    user: "50000:50000"
    command:
      - -c
      - |
        /opt/airflow/wait-for-it.sh database:5432 -- echo "database is up"
        airflow db init
        airflow users create --firstname Jose --lastname Nunes --email admin --password admin --username admin --role Admin

  prometheus-statsd-exporter:
    image: prom/statsd-exporter:v0.23.3
    container_name: prom-statsd-exporter
    ports: 
      - 9102:9102
    networks: 
      - airflow
    command: ["--log.level=debug"]
